version: '3.8'

services:
    app:
        build: .
        container_name: hotel_reservation_app
        ports:
            - "8000:9000"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: hotel_reservation
            DB_USERNAME: root
            DB_PASSWORD: secret
        depends_on:
            - db
        volumes:
            - .:/var/www/html  # Sync the app code for development
        networks:
            - hotel_network

    db:
        image: mariadb:latest
        container_name: hotel_reservation_db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: hotel_reservation
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - hotel_network

networks:
    hotel_network:

volumes:
    dbdata:
