name: Deploy Laravel to EC2

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Deploy to EC2 as faraimrape
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su - faraimrape <<'EOF'
            echo "Starting deployment"

            # Ensure the deployment directory exists
            mkdir -p /home/faraimrape/htdocs/resrequest.faraimrape.site/

            # Sync the Laravel project from GitHub to the EC2 instance
            rsync -avzvv --delete --exclude '.env' --exclude 'storage' --exclude 'vendor' ./ /home/faraimrape/htdocs/resrequest.faraimrape.site/

            # Change directory to the Laravel project
            cd /home/faraimrape/htdocs/resrequest.faraimrape.site/

            # Install Composer dependencies
            composer install --optimize-autoloader --no-dev

            # Generate the .env file if it does not exist
            if [ ! -f .env ]; then
              cp .env.example .env
              php artisan key:generate
            fi

            # Run database migrations
            php artisan migrate --force

            # Cache configurations and routes
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Set correct permissions for storage and cache directories
            chown -R faraimrape:faraimrape storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            # Restart PHP-FPM if using it
            sudo systemctl restart php8.3-fpm

            echo "Laravel deployment complete."
            EOF
