name: Deploy Laravel to EC2

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    name: 🎉 Laravel Deployment Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync Files to EC2 as `faraimrape` user
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/faraimrape/htdocs/resrequest.faraimrape.site/
          remote_host: ${{ secrets.EC2_INSTANCE_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # The following command ensures you switch to `faraimrape` user when syncing
          script_before_deploy: |
            sudo su - faraimrape

      - name: 🚀 Run Deployment Commands as `faraimrape` user
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Switch to the correct user
            sudo su - faraimrape <<'EOF'
            cd /home/faraimrape/htdocs/resrequest.faraimrape.site

            # Install dependencies
            composer install --optimize-autoloader --no-dev

            # Run migrations
            php artisan migrate --force

            # Clear and cache config/routes/views
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Set correct permissions
            sudo chown -R faraimrape:faraimrape storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Restart PHP-FPM (if using)
            sudo systemctl restart php8.3-fpm

            # Optionally clear any previous cache
            php artisan optimize:clear

            echo "Laravel deployment complete."
            EOF
