name: Deploy Laravel to EC2

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Deploy to EC2 as faraimrape
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su - faraimrape <<'EOF'
            echo "Starting deployment"
            # Sync files using rsync
            rsync -avzvv --delete --exclude '.env' --exclude 'storage' --exclude 'vendor' ./ /home/faraimrape/htdocs/resrequest.faraimrape.site/

            # Debugging: List files after rsync
            ls -la /home/faraimrape/htdocs/resrequest.faraimrape.site/

            # Navigate to your Laravel project
            cd /home/faraimrape/htdocs/resrequest.faraimrape.site/

            # Install dependencies
            composer install --optimize-autoloader --no-dev

            # Run migrations
            php artisan migrate --force

            # Clear and cache config/routes/views
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Set correct permissions
            sudo chown -R faraimrape:faraimrape storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Restart PHP-FPM (if using)
            sudo systemctl restart php8.3-fpm

            echo "Laravel deployment complete."
            EOF
